spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pokemonapi?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
